### ISSUE TITLE
Unable to capture gRPC

### ISSUE THREAD

**Issue by skords** [httptoolkit/frida-interception-and-unpinning#113]
I am trying to find the gRPC communications happening inside the app: https://get.wirspway.com/

- I tried using the android scripts with Burp and mitmproxy but both failed to capture anything.
- While using the android script with mitmproxy, it shows the message that `The client does not trust the proxy's certificate`
- When I set the proxy manually in the wifi settings and added the CA cert, I got basic traffic
- The command I am using: `frida -U -l ./config.js -l ./native-connect-hook.js -l ./native-tls-hook.js -l ./android/android-proxy-override.js -l ./android/android-system-certificate-injection.js -l ./android/android-certificate-unpinning.js -l ./android/android-certificate-unpinning-fallback.js -f com.xioy.sle`
- I tried HttpToolkit with Adb feature (with VPN) and it managed to capture all https requests perfectly. The issue is that I do not see any gRPC communication being captured.
- I tried manually adding the gRPC port that is being used by the app i.e. 10001-10004 and the app stopped working completely (may be it is unable to forward the packets properly?)
- I have also tried using apk modifiers but the app validates the md5 hash of every file on startup with an api
- After some workarounds, I managed to see the packets being sent to HTTP toolkit app but the app is unable to parse them as it does not really support gRPC. How do I parse them?
![image](https://github.com/user-attachments/assets/3518515a-358b-49f0-84cd-dc29ea82d745)

I am new to Frida and Http Toolkit. Any help will be appreciated.

**Comment by pimterry** [comment]
The garbled message shown there is not gRPC. gRPC traffic generally looks like protobuf messages sent over HTTP/2, so you should see a normal HTTP method, headers & URL etc. That message is not any kind of HTTP. It's some other non-HTTP protocol or traffic, and you won't be able to explore that with HTTP Toolkit.

Otherwise, in general GRPC is supported. There are some limitations and challenges in places, but it should mostly work.

> I tried manually adding the gRPC port that is being used by the app i.e. 10001-10004 and the app stopped working completely (may be it is unable to forward the packets properly?)

How do you know those ports are being used for gRPC?

When this fails, do you see anything in HTTP Toolkit at all? Is than when the garbled message above appears?

**Comment by skords** [comment]
> The garbled message shown there is not gRPC. gRPC traffic generally looks like protobuf messages sent over HTTP/2, so you should see a normal HTTP method, headers & URL etc. That message is not any kind of HTTP. It's some other non-HTTP protocol or traffic, and you won't be able to explore that with HTTP Toolkit.
> 
> Otherwise, in general GRPC is supported. There are some limitations and challenges in places, but it should mostly work.
> 
> > I tried manually adding the gRPC port that is being used by the app i.e. 10001-10004 and the app stopped working completely (may be it is unable to forward the packets properly?)
> 
> How do you know those ports are being used for gRPC?
> 
> When this fails, do you see anything in HTTP Toolkit at all? Is than when the garbled message above appears?

Alright, what you're saying makes sense. It might not be gRPC at all. However, messages look encrypted and have a socket-like behavior (saw ping-pong style exchange on Wireshark).

> When this fails, do you see anything in HTTP Toolkit at all? Is than when the garbled message above appears?

No I can't see anything in HTTP toolkit at that time. I had to run the app first and then start HTTP toolkit via adb to see the messages.

**Comment by pimterry** [comment]
> Alright, what you're saying makes sense. It might not be gRPC at all. However, messages look encrypted and have a socket-like behavior (saw ping-pong style exchange on Wireshark).

These messages are definitely not HTTP, and it's not any remotely normal version of gRPC (it's possible to do non-HTTP gRPC with custom transports in any protocol you like - but it's very very unusual). I don't know what traffic this is, but there is zero chance that HTTP Toolkit (or any other similar HTTP debugging tools) is going to be able to read this for you. This isn't a small issue of configuration - you need to use different tools and do something completely different.

Your only option to read this data is to use Wireshark or similar, to read and parse the raw bytes for yourself. If it's encrypted, you'll need to get the key and decrypt it by hand.

I'm going to close this, since it's not HTTP related. Feel free to reply with more info if you do have any issues with HTTP traffic specifically, but any cases like this where the message is shown as being totally unparseable, then means that it's some non-HTTP protocol, and an HTTP debugging tool is not going to work for you.
