### ISSUE TITLE
Failed to attach: closed

### ISSUE THREAD

**Issue by Jiroun** [httptoolkit/frida-interception-and-unpinning#65]
Hello , Any one Faced this problem ?
know how to solve this

PS C:\Users\al\Downloads> frida -U -l ./config.js -l ./android-certificate-unpinning.js -f com.wXXXXX.XXXXX
     ____
    / _  |   Frida 16.1.8 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Android Emulator 5554 (id=emulator-5554)
Failed to attach: closed
PS C:\Users\al\Downloads>

**Comment by pimterry** [comment]
No idea I'm afraid. Maybe the ADB connection you're using is unstable? Could even be a dodgy USB cable.

Does it happen with other apps on the same device? If not, this could be some kind of Frida detection mechanism inside the app itself.

Does it happen if you don't use these scripts at all? (i.e. if you run just `frida -U -f com.XXX`). If so, it's probably best to look at the Frida repo instead of here: https://github.com/frida/frida/

**Comment by Jiroun** [comment]
> No idea I'm afraid. Maybe the ADB connection you're using is unstable? Could even be a dodgy USB cable.
> 
> Does it happen with other apps on the same device? If not, this could be some kind of Frida detection mechanism inside the app itself.
> 
> Does it happen if you don't use these scripts at all? (i.e. if you run just `frida -U -f com.XXX`). If so, it's probably best to look at the Frida repo instead of here: https://github.com/frida/frida/

Thanks for your response , actually I am on emulator , no need usb
Just tried on youtube , same problem

PS C:\Users\al\Downloads> frida -U -l ./config.js -l ./android-certificate-unpinning.js -f  com.google.android.youtube
     ____
    / _  |   Frida 16.1.8 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Android Emulator 5554 (id=emulator-5554)
Failed to attach: closed
PS C:\Users\al\Downloads>


 frida -U -f com.google.android.youtube
even this not worked 


I put the same ca-certificate here
C:\Users\al\AppData\Local\httptoolkit\Config\ca.pem

in the config 

is this ok?

**Comment by pimterry** [comment]
> frida -U -f com.google.android.youtube
> even this not worked

Ok, that means it's not related to these scripts (and so your config doesn't matter either). It's somebody about your emulator, or about how you're running Frida. You'll need to debug those separately I'm afraid.

I'm going to close this issue, since this repo is just focused on these scripts, and that means this isn't related. For issues with Frida in general like this, you should talk to the Frida team at https://github.com/frida/frida/ (stack overflow etc are also often good for this kind of thing).

**Comment by 3052** [comment]
I dont think YouTube uses pinning, but it does use QUIC. but turns out if you block outbound UDP port 443 then YouTube uses HTTP/2 instead - so I am able to capture the Android client now
