### ISSUE TITLE
Failed to spawn process

### ISSUE THREAD

**Issue by glaaam13371** [httptoolkit/frida-interception-and-unpinning#71]
Hi, i got this error
![image](https://github.com/httptoolkit/frida-interception-and-unpinning/assets/159718183/96a6f672-aad1-4393-805f-35518299d033)
What can i do ?

**Comment by pimterry** [comment]
Can you share the full command you're using? You've cut that off in the screenshot.

What device, OS version & jailbreak are you using?

At a glance it looks like this is probably a general Frida issue, rather than something to do with these scripts. I'm happy to make some guesses, but I expect you'll probably have more luck looking through the [Frida issues](https://github.com/frida/frida/issues) or opening an issue there.
