### ISSUE TITLE
Error with file : android-certificate-unpinning.js

### ISSUE THREAD

**Issue by Avilash1234** [httptoolkit/frida-interception-and-unpinning#95]
"
SyntaxError: redeclaration of 'NO_OP'
    at <eval> (/home/avilash/frida-interception-and-unpinning/android/android-certificate-unpinning.js:1)
"

I'm getting this error when trying to use this script.

**Comment by pimterry** [comment]
That means in the combination of all the scripts you're using, there's two places where "NO_OP" is declared at the top level. In these scripts that only happens once: [here](https://github.com/httptoolkit/frida-interception-and-unpinning/blob/04999618318247f0db33dd3b703383a70d773e53/android/android-certificate-unpinning.js#L72) in `android/android-certificate-unpinning.js`, so that means you're either adding that script twice on the command line (in which case you'll want to remove one of those), or you're using another script from somewhere else that also defines this (in which case you'll need to modify one of the scripts to fix this).

Either way, this isn't a problem with the scripts here (it's a problem with the specific setup of how you're using Frida and/or the other script you're using too) so I'm going to close this.
